### ISSUE TITLE
Some textures not working with BYG and BetterEnd mods; Flying issues.

### ISSUE THREAD

**Issue by RDKRACZ** [TheEpicBlock/PolyMc#103]
1. Short Grass; Rainbow Eucalyptus Log; Willow Log; Meadow Dirt; Water Silk. These blocks have the textures of the stone in-game but in the resource pack, they have the correct textures. Image below.

<details>

![2021-08-18_00 14 39](https://user-images.githubusercontent.com/43277609/129808596-b0502907-3881-4be0-a9e2-749192028296.png)

</details>

2. The worse thing is... you can fly in survival when BYG and PolyMC are installed on the server. It kinda looks like you are always in water / on a ladder. You descend slow but get fall damage, sprinting is even more broken. The same thing happens in the creative mode (but not in the Spectator mode).

Also, I used not yet released 1.17 Fabric BYG built from here https://github.com/CorgiTaco/BYG/tree/Fabric-1.17.X.

**Comment by RDKRACZ** [comment]
Btw PolyMC for 1.17 generates resource pack with `"pack_format": 6` instead of `7`.

**Comment by RDKRACZ** [comment]
Seems like the same issues happen with the BetterEnd mod? I may be doing something wrong then or it's just some things are not developed yet?
That being said PolyMC works great with the More Gems mod.

**Comment by FrostBird347** [comment]
I have also noticed this issue with the BetterEnd mod and I do not have BYG installed.
When the player is above or below the world they will fall normally.

Majority of BetterEnd's textures also fail to be generated. It's unlikely that this is connected to this issue, however it is worth mentioning (When testing I had a few other mods enabled, slightly increasing the number of textures in the generated resource pack):
- Files in BetterEnd's block texture folder: 1028
- Files in the generated block texture folder: 218
- Files in BetterEnd's item texture folder: 176
- Files in the generated item texture folder: 57

While this likely will not help, I have attached the logs made when the server generated the resource pack.
[resource.log](https://github.com/TheEpicBlock/PolyMc/files/7006553/resource.log)

<details>
<summary>Mod List </summary>

- better-end-0.11.0-pre
- betterbeds-1.2.0
- customizableelytra-fabric-1.4.0-1.17
- krypton-0.1.4
- minitweaks-1.1.1
</details>
(Only mods that modify/create items/blocks or modify the network protocol are listed)

**Comment by TheEpicBlock** [comment]
Your first issue is to be expected. Some of those are [complicated blocks](https://theepicblock.github.io/PolyMc/status.html#blocks-) that PolyMc can't handle. For the other ones you might've run out of blocks. I can't tell for sure unless you provide the polydump made using `/polymc generate polyDump`. In the case of BetterEnd, it uses some custom resource generation.

I will have to look into your second issue. A similar issue has happened before where a modded block was entered into the water tag and the client didn't recognize it and replaced it with water instead. That should be fixed though.

**Comment by FrostBird347** [comment]
> I can't tell for sure unless you provide the polydump made using `/polymc generate polyDump`. 

Here is the polydump
[PolyDump.txt](https://github.com/TheEpicBlock/PolyMc/files/7007678/PolyDump.txt)

**Comment by FrostBird347** [comment]
I have noticed that both void and cave air are not affected by this bug, so a temporary, laggy and very messy fix (that could have other consequences that I have not thought about) would be to replace the air blocks near the player with void or cave air through a datapack or command block.
