### ISSUE TITLE
Implement Blocks

### ISSUE THREAD

**Issue by YTG1234** [TheEpicBlock/PolyMc#11]
This is a feature suggestion to allow modded blocks and not only items.

**Comment by TheEpicBlock** [comment]
I'm working on this right now. It's looking good. A basic system should be coming soon™
[This](https://github.com/TheEpicBlock/PolyMc/wiki/Status) page contains everything I plan to add together with how far I am with it.

**Comment by YTG1234** [comment]
Thank you for letting me know! I think this mod is going to be an awesome tool for server owners who want to make a modded server with Vanilla clients able to connect. Looking forward to this project.

**Comment by TheEpicBlock** [comment]
With 2.0.0 basic blocks have been implemented. It will be improved over the next few updates!
