### ISSUE TITLE
Incantationem enchantments do not show

### ISSUE THREAD

**Issue by TheEpicBlock** [TheEpicBlock/PolyMc#117]

**Comment by slidedrum** [comment]
As far as I can tell, it does not work with any enchantment mods.  but it only affects books.  Enchants on tools and everything else I have seen still work.  If I understand correctly, giving the books the lore NBT tag that the tools get should fix this.  

Please ignore the comment I made in discord about it working with some enchantment mods, I had one enchant mod on my client that was causing my client to see it.

**Comment by TheEpicBlock** [comment]
In that case, this should be fixed in dev when I fixed #107.

**Comment by slidedrum** [comment]
I just tested it with a clone of the latest source code, and it does not appear to be fixed.  From what I understand it is caused by ItemStack's getEnchantments method only getting the "Enchantments" tag, and not the "StoredEnchantments" tag that enchanted books use.
