### ISSUE TITLE
Config option for block and entity overrides

### ISSUE THREAD

**Issue by FrostBird347** [TheEpicBlock/PolyMc#120]
A config option to override specific block and entities would help a lot.
This will help a lot with mods that have blocks which are represented as stone blocks, even though their models might fit a vanilla block's hitbox.
For example: The sculk vein block in the [Wild Update Mod](https://www.curseforge.com/minecraft/mc-mods/the-wild-mod) is represented as a stone block, however it does not have a hitbox and would be better represented as either a single snow layer, some carpet with a custom model or even an air block.

In addition to adding block overrides, entity overrides would also be great.
Currently all modded entities are represented as pigs and I don't see any reason why it would be difficult to replace them with other vanilla entities, unlike using custom entity models which will take a long time to implement and while far better, will likely fall back to pigs for the occasional entity, similar to other modded blocks.

**Comment by FrostBird347** [comment]
This is similar to issue #30, however I am not asking to add support for clients without the resource pack and am instead asking for an option to specify the block model used, as a workaround for stone blocks.

**Comment by TheEpicBlock** [comment]
The api provides the functions you've described, including the entities. A simple way to access this would be better suited for a separate mod. 
By the way, PolyMc should be able to poly blocks without collisions, you may have too many blocks or PolyMc might not be able to correctly recognise it.

**Comment by FrostBird347** [comment]
> The api provides the functions you've described, including the entities. A simple way to access this would be better suited for a separate mod. By the way, PolyMc should be able to poly blocks without collisions, you may have too many blocks or PolyMc might not be able to correctly recognise it.

Unless if I am mistaken, to access the API you need to modify the mod in question or make your own mod, instead of from a config setting.

But even if a config option fo block overrides does not get added due to the API's existence, I still think you should consider adding a way to do something similar with entities, whether that's through the API or a config option.

**Comment by TheEpicBlock** [comment]
An easier way to change polys for either blocks or entities is a good idea, I just don't think it would be a great idea to have it in base PolyMc, doing it in another mod is better
