### ISSUE TITLE
Assets are not found if the block/item namespace does not match the modid

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#121]
I think the resource pack maker currently assumes that block & item namespaces will always match the modId, but this isn't always the case.

Different mods, with different modIds, can register blocks/items to a shared namespace.
In that case the resource pack maker won't be able to find the assets using the current implementation.

The easiest solution might be to let mods declare to PolyMC which namepaces they're using?

**Comment by Patbox** [comment]
Otherway to work around it would be just checking of all mod jars for resources and copying when needed

**Comment by TheEpicBlock** [comment]
This should be fixed once I refactor the whole resource handling. We should be able to index which jars contain which namespaces and we should be able to reuse Minecraft's logic for this.

**Comment by TheEpicBlock** [comment]
(for a quick fix, the advanced resource generation option copies everything into a folder before using it. That should also fix this but it's not the best of solutions)

**Comment by skerit** [comment]
Ah good to know, I'll go with the advanced resource generation for now then.

**Comment by TheEpicBlock** [comment]
This (should) be fixed in b88ee00cc9fb85a937e65a8dbe151039b9a574c8
