### ISSUE TITLE
Items in item frames show their name

### ISSUE THREAD

**Issue by GlowingUmbreon** [TheEpicBlock/PolyMc#123]
As you can see in the below screenshot the custom items name shows up even though it has not been named through a nametag, this should be changed so items in item frames do not send their name unless it has a custom name.
![image](https://user-images.githubusercontent.com/37640997/145718612-6d192ed7-2690-417f-8c71-b6227528e346.png)
Very minor bug :P

**Comment by skerit** [comment]
Ah, that might seem like a minor bug, but fixing it won't be trivial.
The thing is: the only way to get vanilla items have a different name on the client-side is by actually giving it a custom name.
So according to the client, this item (which might be something like a re-textured iron nugget or something) really does have a custom name.

So the fix would be to only set a custom name for items not in an item frame, but I'm not sure if it's worth the extra trouble.

**Comment by TheEpicBlock** [comment]
Having the location of an item would actually be kind of useful. It should make #13 possible as well

**Comment by Patbox** [comment]
It's not too bad to fix, you just need to put some custom/replacing logic in one of packets (polymer has it for example)

**Comment by GlowingUmbreon** [comment]
> It's not too bad to fix, you just need to put some custom/replacing logic in one of packets (polymer has it for example)

Yeah this is what I was thinking the fix would be.
