### ISSUE TITLE
Can we use the "PolyMC" name for our own Software?

### ISSUE THREAD

**Issue by binex-dsk** [TheEpicBlock/PolyMc#126]
I have made a fork of MultiMC called [PolyMC](https://github.com/PolyMC/PolyMC). Someone told me that the name is already used by this repository--so I'm asking if it's alright with you for us to use this name. Thank you!

**Comment by TheEpicBlock** [comment]
I'm fine with you using the name, after all I don't own really own it. Thanks for asking though!

**Comment by binex-dsk** [comment]
Thank you very much! Appreciated.

**Comment by Heath123** [comment]
It is a little confusing to have two projects with the same name they're both somewhat established/popular now so I suppose it's too late for either to change

**Comment by vadim-a-yegorov** [comment]
> I'm fine with you using the name, after all I don't own really own it. Thanks for asking though!

Now when I search "PolyMC" I can't even find our compatibility lib https://github.com/TheEpicBlock/PolyMc, all I see is news headlines. Btw I don't care about *leftoids* etc bullshit.

**Comment by Leguan16** [comment]
What is the purpose of this message?

**Comment by TheEpicBlock** [comment]
Yep, this was a mistake on my part, allowing them to use the name has caused some confusion. However, the launcher is dead now and nobody who actually uses PolyMc much seems to be really confused. There might be a point in renaming it for blanketcon but as of now I've got no plans yet

**Comment by vadim-a-yegorov** [comment]
I think renaming is a good idea, I personally facing difficulties when trying to search this project.
