### ISSUE TITLE
[Suggestion] [Documentation] List of Servers using PolyMC

### ISSUE THREAD

**Issue by chibbi** [TheEpicBlock/PolyMc#132]
### What
A list of servers which use PolyMC. 
This list would be inside of the PolyMC documentation and at least show the ip/domain of the server. In the best case, the list would also explain in what capacity the server is using PolyMC.
The Documentation should point to this list in the "What is PolyMC?" section.
Any serverowner could create an issue or even add himself to this list inside via a pull request.

In the best case, i think PolyMC should have its own server which can serve as a tech demo, where complicated mods are showcased to work with vanilla clients. But this would require founding so it is probably not realistic.

### Why
This would be helpful for PolyMC as people just discovering it, can quickly try it out on an already running server and the server will get a little promotion for itself, which makes this a good trade for both sides i think.

If this is approved, i could add the section and references to the section.

**Comment by TheEpicBlock** [comment]
Afaik there are no public servers using PolyMc. Even then I don't think know if I want to maintain such a list. If anyone reading this does make a public server please do let me know though :D. Hosting a demo server is a good idea and might be a thing I do in the future.
