### ISSUE TITLE
[Suggestion] [Documentation] Issue templates

### ISSUE THREAD

**Issue by chibbi** [TheEpicBlock/PolyMc#133]
### What
Creating issue templates for this repository.
Or even just use the default github templates.

### Why
Issues are quickly becoming unorganized and hard to read and even lack needed information, if they are written without templates.
Templates make sure, that people creating an issue, know that they should answer questions like what version are they using ,what the problem is exactly, why it is a problem, how to reproduce the problem.
They also enable automated labeling, as you can have a template for documentation enhancement, feature requests, bugs, which all have their own labels assigned by default. That way you don't need to wait for a contributor, to manually label them. This will also make sure that contributors don't have to waste there time trying to find out what this issue is actually about, as it is immediatly properly labeled.

**Comment by TheEpicBlock** [comment]
I've decided I'm not going to bother. Having templates locks stuff into certain categories and the bug tracker is small enough that I can easily handle the organisation. I will try to keep the tags sorted better though
