### ISSUE TITLE
Improve support for armor

### ISSUE THREAD

**Issue by CamperSamu** [TheEpicBlock/PolyMc#134]
Because of the way Minecraft is coded, using warped fungus on a stick for armor won't display the armor model, but the armor texture.

**Comment by CamperSamu** [comment]
Maybe do that whenever an item specifies attribute modifiers where a armor piece it uses chainmail armor with  custom model data applied?
I don't remember if there's an easy way to define wearable armor...

**Comment by TheEpicBlock** [comment]
This alongside fancy pants support will come soon™ once the resource rewrite is done. A workaround for now is to right click the armor whilst holding it.

**Comment by CamperSamu** [comment]
Ok thanks!
