### ISSUE TITLE
Lang file encoding error

### ISSUE THREAD

**Issue by Soochaehwa** [TheEpicBlock/PolyMc#140]
![2022-03-01_05 18 14](https://user-images.githubusercontent.com/43947445/156052997-1b8a3cef-5f9b-45d0-bb3c-183777cb5ff3.png)
Non-English characters are not displayed correctly.

**Comment by TheEpicBlock** [comment]
I couldn't reproduce this with some Greek characters. Could you give a mod that triggers this?

**Comment by Soochaehwa** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric
I used this mode.

**Comment by TheEpicBlock** [comment]
Just generated a resource pack using that mod and found the resulting file to use the exact same characters. Were you using the latest version of PolyMc (4.0.0)?

**Comment by Soochaehwa** [comment]
I used polymc 4.0.0
list of mods used
- advancednetherite-fabric-1.4.1-1.18.2
- fabric-api-0.48.0+1.18.2
- PolyMc-4.0.0+1.18.2 

[lang.zip](https://github.com/TheEpicBlock/PolyMc/files/8399055/lang.zip)
This is the lang file of the resource pack I created with polymc

**Comment by Zekiu** [comment]
Korean lang file from Advanced Netherite is encoded in UTF-8, while PolyMC's Korean lang file is encoded in EUC-KR, according to Soochaehwa's attached file (for some reason when I generate resources the file is encoded in UTF-8, but all korean characters are question marks). This issue probably also relates to Polish characters not being displayed correctly, as PolyMC's Polish lang file is encoded in ANSI where it should also be encoded with UTF-8. 
**Ideally PolyMC would have to convert all lang files to UTF-8 automatically if possible.**

Some screenshots of before and after converting lang files to UTF-8:
Before: 
![image](https://user-images.githubusercontent.com/68301723/163868636-c013c73b-f72c-446f-85e5-a70751b9b35f.png)
![image](https://user-images.githubusercontent.com/68301723/163868688-2c8271ae-b045-464a-8663-6c80759c6617.png)
After:
![image](https://user-images.githubusercontent.com/68301723/163868963-39f4c2ce-045a-450d-9100-f87a1b8c818c.png)
![image](https://user-images.githubusercontent.com/68301723/163868998-7c64812f-68f8-4f28-a2bb-809ef45a2e54.png)

Minecraft version: 1.18.2
Mods used:
- PolyMC 4.1.0
- Fabric API 0.50.0
- Advanced Netherite 1.4.1 (for Korean lang file)
- Dense Ores: Refabricated 1.2.2 (for Polish lang file)

**Comment by TheEpicBlock** [comment]
Oh yeah, I kept looking at reading the lang files I forgot PolyMc writes lang files too. FileWriter's use their platform's default charset which is why I couldn't reproduce this.

**Comment by Soochaehwa** [comment]
![2022-06-25_22 55 09](https://user-images.githubusercontent.com/43947445/175776723-3c367a65-b6db-4245-9a1f-89de51b31319.png)
Unfortunately, it hasn't been fixed.

Mods list
- Croptopia-1.19-FABRIC-2.0.5
- fabric-api-0.56.3+1.19
- PolyMc-5.1.0+1.19
- polymer-all-0.2.2+1.19

[lang.zip](https://github.com/TheEpicBlock/PolyMc/files/8984885/lang.zip)

**Comment by TheEpicBlock** [comment]
Looks like I reintroduced this during some resource gen refactoring
