### ISSUE TITLE
resource pack

### ISSUE THREAD

**Issue by Skywalker8510** [TheEpicBlock/PolyMc#148]
when I put the resource pack into the Minecraft resource packs folder it doesn't show up in the game

**Comment by TheEpicBlock** [comment]
Please make sure you've copied the right folder and that you've copied it to the right location. It should be the entire resource folder. Also make sure there's a pack.mcmeta file

**Comment by Skywalker8510** [comment]
so don't take the stuff in the resources folder take the entire resources folder

**Comment by TheEpicBlock** [comment]
Yes, you can rename the folder if you please.
