### ISSUE TITLE
Armors displays negative durability 

### ISSUE THREAD

**Issue by Zekiu** [TheEpicBlock/PolyMc#149]
This happens when modded armor has higher durability than leather armor and it gets damaged below that point.
![image](https://user-images.githubusercontent.com/68301723/164744320-1d899682-c86b-41b3-9147-873dfc64901b.png)

Minecraft version: 1.18.2
PolyMC version: latest master 5158065236af51d3e5df915913c343db43deab86 (does NOT happend on PolyMC 4.1.0)

**Comment by TheEpicBlock** [comment]
Forgot to push my latest commit, that should fix it <3
