### ISSUE TITLE
Discord server (or similar)

### ISSUE THREAD

**Issue by Heath123** [TheEpicBlock/PolyMc#15]
Would it be possible for you to make a Discord or similar chat room? This looks really interesting and I'd like to follow it.

**Comment by TheEpicBlock** [comment]
I'll need to look into this. But it's definitely an option. For now I'll keep on posting in the fabricord and in the fabric serverside development discord.

**Comment by CamperSamu** [comment]
can you send me a link to the Fabric Server-side development discord?

**Comment by TheEpicBlock** [comment]
https://discord.gg/ufhg8dh
This should be a permanent link. I'm going to close this for now.

**Comment by CamperSamu** [comment]
thanks!
