### ISSUE TITLE
Unknown or incomplete command

### ISSUE THREAD

**Issue by BlueAmulet** [TheEpicBlock/PolyMc#157]
fabric 0.14.6
blockus-2.4.7+1.18.2
fabric-api-0.53.3+1.18.2
PolyMc-4.1.2+1.18.2

When trying to use the polymc generate command, the server says "Unknown or incomplete command"
I can see the polymc command registerd in /help however.

**Comment by TheEpicBlock** [comment]
Are you sure you're using the correct command? It should be `/polymc generate resources`

**Comment by BlueAmulet** [comment]
Yes, when running the polymc command it just complains that it doesn't know the command

**Comment by TheEpicBlock** [comment]
Well yes, the PolyMc command on its own doesn't do anything, and it will display as an unknown command iirc

**Comment by BlueAmulet** [comment]
Oh, then I suppose the scope of this issue is to add some basic output to incomplete forms of the command then, cause it felt like the mod was broken in some way. Feel free to close or not.

**Comment by TheEpicBlock** [comment]
All of Minecraft's commands give the same error when run without the full arguments, so I'm just going to follow their lead. Thanks for reporting though :D
