### ISSUE TITLE
[enhancement] is it possible to make this work with the geyser mod

### ISSUE THREAD

**Issue by Skywalker8510** [TheEpicBlock/PolyMc#188]
it would be really cool if this could work with the geyser mod to allow bedrock players to play on modded java servers. I don't know how all of this magic works tho so I have no idea if it's even possible. but I assume it would just involve a bedrock texture pack being created along with the java one.

**Comment by TheEpicBlock** [comment]
It's not just creating resource pack. You'd need to integrate with Geyser for example to implement items, because cmd doesn't exist. Please read the faq https://theepicblock.github.io/PolyMc/faq

**Comment by Hiho2950** [comment]
try after exporting resource pack of java add a pack.mcmeta file then zip them then use this https://github.com/Kas-tle/java2bedrock.sh/
