### ISSUE TITLE
Mod incompatibily when Lootr and PlayerEx mods are both installed at the same time

### ISSUE THREAD

**Issue by elhertz** [TheEpicBlock/PolyMc#189]
I'm having an issue with mod incompatibility with a specific mod configuration

- PolyMC + Lootr = Good
- PolyMC + PlayerEx & DataAttributes = Good
- Lootr + PlayerEx & DataAttributes = Good
- PolyMC + Lootr + PlayerEx & DataAttributes = Crash

Crash log: https://pastes.dev/aBHKIrSV3a

Mod links:
https://www.curseforge.com/minecraft/mc-mods/playerex
https://www.curseforge.com/minecraft/mc-mods/data-attributes (PlayerEx's dependency)
https://www.curseforge.com/minecraft/mc-mods/lootr-fabric

**Comment by TheEpicBlock** [comment]
This is primarily a conflict with data attributes, which prevents PolyMc from inspecting entities, it just only crashes with PlayerEx because data attributes doesn't add any entities by itself.

**Comment by TheEpicBlock** [comment]
Note: this does mean that automatic entity polying doesn't work when data-attributes is installed.
