### ISSUE TITLE
Poly mc block's are broken, but not the item of the block.

### ISSUE THREAD

**Issue by masterblaster221** [TheEpicBlock/PolyMc#197]
I start up the server on Quilt and generate resources and added them to the server but a strange thing happens every single modded block breaks, even one that worked before it just turns to stone the really weird part is that the block in my inventory has their modded textures but when I place it turns to stone.  (I tried this on fabric to the same thing happened)

[PolyDump (1).txt](https://github.com/TheEpicBlock/PolyMc/files/10229425/PolyDump.1.txt)

**Comment by masterblaster221** [comment]
Oh and this is my mod list. 
![Capture](https://user-images.githubusercontent.com/35042730/207652651-82d94045-753f-43f6-9c5f-7f3c0efaf66b.PNG)

**Comment by masterblaster221** [comment]
If you need any other info just ask

**Comment by masterblaster221** [comment]
Here is my Polymc config 
{
  "configVersion": 10,
  "disabledMixins": [
    "CustomPacketDisabler"
  ],
  "misc": {
    "processSyncedBlockEventServerSide": [
      "minecraft:note_block"
    ]
  },
  "remapVanillaBlockIds": true,
  "enableWizardThreading": true,
  "maxPacketsPerSecond": 600,
  "forceBlockIdIntControl": true
}

**Comment by masterblaster221** [comment]
If you need any other info just ask.

**Comment by masterblaster221** [comment]
oh and here is my console log. https://pastebin.com/GFsnqwHH

**Comment by TheEpicBlock** [comment]
PolyMc tries assigning blocks to the first thing it finds. In this case, blocks were assigned to various `mcwroofs` blocks. You might want to try [PolyConfig](https://github.com/TheEpicBlock/PolyConfig) to prioritize certain blocks. Or you can use it to "blacklist" less important blocks by assigning them stone (or some other block)
