### ISSUE TITLE
Issue with quilt support on 1.19.3

### ISSUE THREAD

**Issue by TheNukeLore** [TheEpicBlock/PolyMc#202]
trying to use polymc on quilt 1.19.3 results in a hard crash. 
[latest.log](https://github.com/TheEpicBlock/PolyMc/files/10407442/latest.log)

**Comment by TheEpicBlock** [comment]
I hope this fixes it, my ide is currently gaslighting me by saying the function didn't change at all. And your stacktrace seems to not reference any method, which is really odd
