### ISSUE TITLE
Fastbench incompatibility: Crafting table not displaying crafting results (builded on 772b1e9)

### ISSUE THREAD

**Issue by CamperSamu** [TheEpicBlock/PolyMc#21]
the crafting table works but does not display items

**Comment by CamperSamu** [comment]
Actually I discovered I messed up, the issue is a incompatibility between Fastbench and PolyMC

**Comment by TheEpicBlock** [comment]
This appears to be an issue with FastBench. When starting a server with only FastBench enabled and joining with a vanilla client the exact same behaviour can be seen. You could ask the FastBench author, but it appears like he intended the mod to be used on both the [client and server](https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric?comment=10) so it might not be able to be fixed.
