### ISSUE TITLE
Needed configuration option to enable PolyMC only for whitelisted mods

### ISSUE THREAD

**Issue by vadim-a-yegorov** [TheEpicBlock/PolyMc#218]
# Description

Needed configuration field to enable PolyMC only for specified list of mods.

# Details

```
"enabledMods": {
    "Lootr"
}
```

**Comment by vadim-a-yegorov** [comment]
I need to specify list of mods that PolyMC should work with, and ignore all other mods. Purpose – I need Lootr mod to work server-side only; other mods should not be involved as they are already presented on the client side which leads to compatibility issues.

**Comment by TheEpicBlock** [comment]
I'm curious as to why you have all the other mods on the client except Lootr (this might give me some insight into use cases for PolyMc)

**Comment by vadim-a-yegorov** [comment]
> I'm curious as to why you have all the other mods on the client except Lootr (this might give me some insight into use cases for PolyMc)

Lootr logically should be server-side but dev doesn't know how to do it. I don't want to overwhelm client-side so I want to make a few mods work through PolyMc.

**Comment by TheEpicBlock** [comment]
I think it'd be better in your case to just install lootr on the server, it shouldn't add much of an additional load on clients at all, and you're already modding the client. If you still want to use lootr serverside, and you're able to program, you can use the PolyMc api to register no-ops for all mods except lootr
