### ISSUE TITLE
Custom enchantment position in Lore

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#219]
A player on my server reported this issue:

![image](https://github.com/TheEpicBlock/PolyMc/assets/755212/5f66e5e6-0ba5-490a-96f5-cefa2be6f086)

The "Owned by" is regular itemstack lore, the `Beheading` is the custom enchantment.

I've noticed this in the code:
https://github.com/TheEpicBlock/PolyMc/blob/a9346854f46184481fa9626ceab7382eb030c25c/src/main/java/io/github/theepicblock/polymc/impl/poly/item/Enchantment2LoreTransformer.java#L32C41-L32C41

The `atBeginning` argument is only set to true when the item containing the enchantment is a custom item.
But why is that? Shouldn't it always be true?

After setting it to true, the issue was fixed.

**Comment by TheEpicBlock** [comment]
I'm guessing there was probably some reason for that, might have something to do with attributes?

**Comment by TheEpicBlock** [comment]
As of the port to 1.20.5 (b0a34b111a7affb5bbe658b913a7dd11d48f796a), the tooltip fixing code has been overhauled. The hacky `atBeginning` stuff has been removed, and it now takes all the properties into account at once to ensure proper ordering. Thus there shouldn't be ordering issues anymore
