### ISSUE TITLE
All mod items and blocks get converted to vanilla on modded client

### ISSUE THREAD

**Issue by C4uTi0N** [TheEpicBlock/PolyMc#220]
I'm using Farmer's delight and Ad Astra on my server and vanilla clients can connect just fine.

But when i use my own modded client which has the same mods as the server, all items and blocks become vanilla items.
![PolyMC issue](https://github.com/TheEpicBlock/PolyMc/assets/45887100/b61788a8-8769-49ca-87c9-a89acd7b6bda)

List of mods on the server (most fo them are server-side-only for optimizations on tweaks)
![image](https://github.com/TheEpicBlock/PolyMc/assets/45887100/8971e3c9-5881-4ef4-9aa5-9bc923acaadf)

**Comment by TheEpicBlock** [comment]
Please make use of [PolyPuck](https://modrinth.com/mod/polypuck) if you want ot join with a modded client

**Comment by C4uTi0N** [comment]
I should've mentioned that my server is 1.20.1, PolyPuck seems to only be updated to 1.18.2

**Comment by TheEpicBlock** [comment]
It should still work on 1.20.1 :)

**Comment by C4uTi0N** [comment]
It seems to work fine, might be a good idea to mark it as 1.20.1 compatible ;)
