### ISSUE TITLE
Custom Potion/Tipped arrow Support

### ISSUE THREAD

**Issue by Helinos** [TheEpicBlock/PolyMc#221]
The haste potion from Additional Additions just displays as an uncraftable potion.
I'm pretty sure all you'd need to do is pass along a CustomPotionColor tag as well as name the item properly

**Comment by TheEpicBlock** [comment]
Colour/name has been fixed since 4f440b1869a33c61263bc97fdf913a9d34d575f8, the tooltip will be fixed in 1.20.5 (d7398dbda9ac1321891ae73b9bda24ef8b2a7e58)
