### ISSUE TITLE
Create Mod Compat Issues

### ISSUE THREAD

**Issue by AwesomeKalin** [TheEpicBlock/PolyMc#222]
The Create Mod works, however some items aren't placeable at all, some need /setblock to work and some just appear as stone. Latest version of both mods on 1.20.1

**Comment by TheEpicBlock** [comment]
Yes, PolyMc [can't do everything](https://theepicblock.github.io/PolyMc/limitations/)

**Comment by AwesomeKalin** [comment]
I was saying that as I know it can't do everything, however it breaks placing blocks, even with /setblock, which shouldn't happen

**Comment by TheEpicBlock** [comment]
What blocks break and in what way? What happens when you do /setblock?

**Comment by AwesomeKalin** [comment]
Whilst I can't give an exact list of blocks that just don't work with /setblock since there are so many blocks in the Create mod, what happens is that after I run the command nothing happens, absolutely nothing

**Comment by TheEpicBlock** [comment]
Have you checked if you can place any other blocks in the place where the create block is? It probably looked (to PolyMc) like the block had no collision and/or no model and/or no selection box. So it probably polyd it with cave air or one of the special wall states. You can also check the poly dump.

**Comment by AwesomeKalin** [comment]
That's probably it. The create mod uses many different model. I believe I did check and I think it worked.

**Comment by AwesomeKalin** [comment]
Great project btw!
