### ISSUE TITLE
How to reload?

### ISSUE THREAD

**Issue by SAGUMEDREAM** [TheEpicBlock/PolyMc#224]
Is there a way to reload PolyMc？ I made a mod that registers content after the game is running, when I add content to the registry all vanilla items from PolyMc disappear when the backpack is opened

**Comment by TheEpicBlock** [comment]
You could call `PolyMc#onRegistryClosed` a second time, after that you need to loop through all the players and call `PolyMapProvider.get(player).refreshUsedPolyMap()`. I think that should do the trick. Although any items that were sent before this might get desynced. And ofc changing the polymap also changes the layout of the resource pack. If you're unlucky a single change might shift every single custommodeldata id.
So yeah, it's possible but do note that this rebuilds everything and should probably not be done often.
