### ISSUE TITLE
Add support

### ISSUE THREAD

**Issue by Hiho2950** [TheEpicBlock/PolyMc#230]
PLS can you add support for 1.20.1 (to use with sinytra connector) or all 1.20.x of forge :(
pls

**Comment by TheEpicBlock** [comment]
You're asking for Forge support? Sorry but I really don't have time to work on that. The only way PolyMc gets Forge support is if someone forks it themselves. If you want to try it on 1.20.1 then you can just revert to the last version that supported it. Don't expect it to work perfectly with a converter though
