### ISSUE TITLE
Error that I got idk why

### ISSUE THREAD

**Issue by Hiho2950** [TheEpicBlock/PolyMc#231]
I use fabric 1.20.2 fabric with polymc and geysermc (because I m a mobile user),
I can break blocks but i can't place blocks or use any executable blocks like chests, beds, doors(i can see that it's opened but I can't pass unless if a villager opened it)
so pls can you fix that or tell me how

**Comment by TheEpicBlock** [comment]
Does the issue happen without PolyMc being installed? Are you using any modded items or blocks at all anywhere?

**Comment by Hiho2950** [comment]
> Does the issue happen without PolyMc being installed? Are you using any modded items or blocks at all anywhere?

no i got it only when i add polymc even without adding mods :(

**Comment by Hiho2950** [comment]
> Does the issue happen without PolyMc being installed? Are you using any modded items or blocks at all anywhere?

i had ask AI he says it can be a collision handler issue or something like that

**Comment by Hiho2950** [comment]
> Does the issue happen without PolyMc being installed? Are you using any modded items or blocks at all anywhere?

It works when i disable cardboard and Icommon :(
but the problem now there is no textures of blocks when i put the block i see stone block but i see the block when it s on my hand

**Comment by CamperSamu** [comment]
> It works when i disable cardboard and Icommon
https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf

**Comment by Hiho2950** [comment]
> > It works when i disable cardboard and Icommon
> 
> https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf

but the plugins works very well in the fabric with cardboard
i think the problem is that polymc use some classes that can't works with some classes by cardboard or the opposite

**Comment by DiamondBrain113** [comment]
> I use fabric 1.20.2 fabric with polymc and geysermc (because I m a mobile user)

If the geysermc is the plugin then you can find a fabric version for it (but you won't be able to use custom block anyway)

**Comment by CamperSamu** [comment]
@Hiho2950 Mods such as Cardboard and Banner won't be supported by anyone in the Fabric ecosystem because they're too intrusive and tend to break everything, the same goes with Geyser + PolyMc (at least until Bedrock compat gets worked on)

If you are using Geyser for Paper via Cardboard (and I'd be surprised if it acutally worked), try the native Fabric version as suggested by @DiamondBrain113: https://modrinth.com/mod/geyser

**Comment by TheEpicBlock** [comment]
If it works without cardboard then the bug is likely to be on their side. If someone finds the source of the incompat then I might be able to do something, but for now I'm going to close this issue

**Comment by Hiho2950** [comment]
> @Hiho2950 Mods such as Cardboard and Banner won't be supported by anyone in the Fabric ecosystem because they're too intrusive and tend to break everything, the same goes with Geyser + PolyMc (at least until Bedrock compat gets worked on)
> 
> If you are using Geyser for Paper via Cardboard (and I'd be surprised if it acutally worked), try the native Fabric version as suggested by @DiamondBrain113: https://modrinth.com/mod/geyser

i use the native the games works right after deleting cardboard but the custom blocks are only stones blocks when i place it but it s in the correct texture when it s on my hand

**Comment by TheEpicBlock** [comment]
Please read the [faq](https://theepicblock.github.io/PolyMc/faq/) :)
