### ISSUE TITLE
A Development Consulting / Reporting Issues

### ISSUE THREAD

**Issue by SAGUMEDREAM** [TheEpicBlock/PolyMc#234]
Would you like to report or ask some development issues/BUGs?

Minecraft Version: 1.20.4

When I want to use "**PolyMapProvider.EVENT.register(player -> {});**" to make a **custom PolyMap**, the player type is ClientConnection instead of ServerPlayerEntity.

**Comment by TheEpicBlock** [comment]
Yes, the polymap now needs to be created before the player entity is. You'll need to do whatever check you need on the client connection unfortunately
