### ISSUE TITLE
Compatibility with Geysermc

### ISSUE THREAD

**Issue by CoolCat25** [TheEpicBlock/PolyMc#235]
I know this has been asked before, but I want to know if this mod would work with Geyser, which allows Bedrock players to connect to Java. I tried to use Mythics Movs previously to no avail, so if someone knows a way to get it to work with bedrock, that would be appreciated.

**Comment by CoolCat25** [comment]
Also I just read the faq and

**Comment by KohlrabitoDev** [comment]
This should be re-opened, this would be an amazing feature & Id love to see it implemented in the future by either polymc or geyser

**Comment by unix-supremacist** [comment]
hydraulic does what polymc does for geyser, so really the thing need is compat with hydraulic

**Comment by CamperSamu** [comment]
never heard of hydraulic before, how's support?

**Comment by TheEpicBlock** [comment]
Hydraulic has not seen any activity lately and there's no working version yet. I'm in the Geyser discord though, and compatibility should be as simple as just registering a nop map for geyser players. I'd advise people to contribute to hydraulic if they want a "PolyMc for bedrock", the geyser discord should have more information about the status of the project

**Comment by virtualspan** [comment]
Edit: Wow, the nop map thing kinda just went over my head

Hydraulic has had some development now and is relatively active, I think maybe it's a good time to start working on compat with Hydraulic. Right now, Hydraulic works pretty well for custom blocks and items, but when you add PolyMC, all custom blocks are noteblocks and items are feathers. Having a feature where PolyMC skips bedrock players would be nice.

**Comment by CamperSamu** [comment]
> compat with Hydraulic

As TEB said, that should be done by Hydraulic by registering a nop polymap on bedrock players

**Comment by virtualspan** [comment]
I created a mod adding compatibility! https://github.com/virtualspan/HydraulicPolyBridge
