### ISSUE TITLE
Possible to configure which blocks get converted?

### ISSUE THREAD

**Issue by AlexanderwithaA** [TheEpicBlock/PolyMc#238]
So I don't know if this is already a thing, but I'd like to be able to stop polymc from converting some blocks since the mods I'm using don't actually use them. Currently I have 6 modded stairs, but the client will only ever see 4 of them ingame nicely hitting that limit.

If this isn't a thing, an overrides list in the polymc config would be nice. The list could allow outright removing that block/item or specifying how its mapped to vanilla blocks/entities.

**Comment by AlexanderwithaA** [comment]
I'm trying to use traverse with polymc. It doesn't look like what it adds is an issue but let me know if it is.

**Comment by TheEpicBlock** [comment]
https://github.com/theepicblock/polyconfig this should help! You can either prioritize certain blocks, or you can replace them with anything that isn't a group (like stone or oak stairs) to make them not count towards the limit anymore.
