### ISSUE TITLE
Blocks only appear correctly after relogging

### ISSUE THREAD

**Issue by xDraxxis** [TheEpicBlock/PolyMc#24]
This is probably already known, but I figured I'd make an issue. Blocks from the Blockus mod only appear after re-logging on to the server. Also they display as noteblocks as opposed to stone which it says inside of the status. (As soon as they get updated they turn to stone, this is with the Blockus mod on clientside as well, and items for said blocks do not actually seem to exist, after doing some more testing, neither blocks nor items seem to appear on a completely 100% vanilla client with serverside resource packs enabled.)

**Comment by TheEpicBlock** [comment]
There was a known issue that blocks didn't get converted correctly when you first load a chunk. This has been fixed if you built it yourself. But the 2.0.0 download doesn't include that fix yet.

The items may appear to not exist. The command would tell you that it's invalid. But if you execute the command it will actually work. Don't know if that's what's

**Comment by TheEpicBlock** [comment]
Accidentally closed this. I'm on a phone :P

**Comment by TheEpicBlock** [comment]
The fact that they appear as noteblocks might be right. As PolyMc remaps modded blocks to noteblocks internally. It might be a sign that you don't have the resourcepack installed correctly.

**Comment by xDraxxis** [comment]
How do you install the resource pack correctly? I edited a bit ago to say they don't appear on the vanilla client at all

**Comment by TheEpicBlock** [comment]
Run the `/PolyMc gen_resource` command. This will generate a resourcepack in the server folder. You'll need to add a pack.mcmeta file yourself and copy it over to your resource pack folder. Note that if you're using the 2.0.0 version it might crash because I messed up. If you built it yourself you'll be fine
