### ISSUE TITLE
The `polymc generate resources` command doesn't generate the `resource` folder

### ISSUE THREAD

**Issue by BreakOrContinue** [TheEpicBlock/PolyMc#246]
I'm using version 5.4.0 with Fabric 1.20.1.
When I run the command `polymc generate resources`, it doesn't generate the `resource` folder. Instead, it generates `polymer-resourcepack.zip` (there is no Polymer on my server), and there are no mod resources in that resource pack.
<img width="558" alt="image" src="https://github.com/user-attachments/assets/80767dac-1fd3-4056-8525-83127ce9cbaf">
(There is Farmer's Delight, Croptopia, and some other mods on my server)
(/polymer-resourcepack/polymer-about.txt)
<img width="557" alt="image" src="https://github.com/user-attachments/assets/d297636a-9a9c-449f-bdc2-6c025c73238d">

**Comment by Patbox** [comment]
You have polymer on the server, just provided/bundled with different mod
