### ISSUE TITLE
Rebrand or distinguish project more to prevent confusion with PolyMC

### ISSUE THREAD

**Issue by LuveelVoom** [TheEpicBlock/PolyMc#247]
There is (unfortunately) a modded minecraft launcher called PolyMC (https://github.com/PolyMC/PolyMC) which was hijacked by one of its lead devs and was "reclaimed from the leftoids"(https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee).
I'm not going to make any overt political statements here, but given that the above launcher has been 1. hijacked by a user with very controversial views 2. may contain malware (there is no evidence to suggest it, but given the user's unstable behavior and sole control over the project it is very possible), it is probably a good idea to change the title/branding of the project (the internal code can remain unchanged) to prevent confusion with this launcher, which could lead to someone accidentally downloading the other launcher or not using PolyMc due to believing it to be the PolyMC launcher.
By the way, if you know anyone who uses PolyMC launcher, tell them to switch to Prism Launcher (https://github.com/PrismLauncher/PrismLauncher) instead, which is a fork of PolyMC made by the former devs of said launcher with the exception of the one that took over it.

**Comment by TheEpicBlock** [comment]
Yes, I'm aware. However, this project has existed longer than the launcher. And the launcher has practically died a long time ago. The confusion because of the similar names is quite limited, and hasn't caused any real issues. So no, I don't want to change the name. The launcher doesn't have exclusive right to it and it never had. Basically, I'd rather reclaim the name than just let a bigoted launcher have it.

**Comment by unix-supremacist** [comment]
i don't really care about if the name changes or not my self but minor correction, polymc is not dead, the prismdevs immediately removed any and all curseforge support from the launcher to appease curseforge, so theres still a lot of people who need curseforge integration held over on polymc including my self, which has made conversations confusing in the past, again i don't personally care though it's not hard to specify (mod) or (launcher) when speaking

**Comment by LuveelVoom** [comment]
> Yes, I'm aware. However, this project has existed longer than the launcher. And the launcher has practically died a long time ago. The confusion because of the similar names is quite limited, and hasn't caused any real issues. So no, I don't want to change the name. The launcher doesn't have exclusive right to it and it never had. Basically, I'd rather reclaim the name than just let a bigoted launcher have it.

Makes sense, hopefully if this project becomes popular enough PolyMC launcher will be forgotten
