### ISSUE TITLE
When will the 1.21 get supported?

### ISSUE THREAD

**Issue by sorae42** [TheEpicBlock/PolyMc#249]
I'm currently running 1.21 and I'd love to get PolyMC for my own server.

**Comment by DinoMarlir** [comment]
same for me

**Comment by CamperSamu** [comment]
PolyMc already supports 1.21.1 but no release has been drafted yet.
If you need a 1.21.1 compatible jar now, you'll have to compile it yourself.

```bash
git clone https://github.com/TheEpicBlock/PolyMc.git
cd PolyMc
./gradlew build
```

**Comment by sorae42** [comment]
Awesome
I will upload the jar on this thread after compile

**Comment by Patbox** [comment]
You can also use the jar from polymania repo https://github.com/Patbox/polymania/tree/master/pack/mods
