### ISSUE TITLE
Breaking Vanilla Blocks is Quicker

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/PolyMc#29]
When mining vanilla blocks (haven't tested with modded), they break much quicker. This causes iron blocks to be almost instant mined with an efficiency V diamond pickaxe.

**Comment by TheEpicBlock** [comment]
There's a big chance I messed the number up. I'll look into it. Thanks for reporting!

**Comment by TheEpicBlock** [comment]
Should be fixed in 0ed3a05 !

**Comment by IAmSneak** [comment]
It seems as if this still happens, but to a slightly lesser degree. You are still able to instant mine stone without a haste II beacon. I am using the latest build.

**Comment by TheEpicBlock** [comment]
The latest commit should fix this. I tested it with stone + eff 5 pickaxe. It was too quick for the breaking animation but the speed seemed to be ok
