### ISSUE TITLE
Allow server hosts to provide block and item replacements in the config

### ISSUE THREAD

**Issue by TrueCP6** [TheEpicBlock/PolyMc#30]

**Comment by TheEpicBlock** [comment]
I'm unsure how useful this is. PolyMC was made to work with a resourcepack. And in that case it doesn't really matter what items/blocks are used. The PolyMC api does already allow for this however. So I might add this as a separate mod

**Comment by TheEpicBlock** [comment]
It's just unreasonable for me to support people who aren't using resource packs. It's hard enough with them. I will write some better documentation for the api though, so then a mod can provide an alternative way of polying things that would work without a resourcepack
