### ISSUE TITLE
Custom Entities idea

### ISSUE THREAD

**Issue by hxr404** [TheEpicBlock/PolyMc#41]
Hello,
first of all, thank you for your great work.
I'm new to github, so I hope its okay to post things that aren't bugs here? If not sorry ;)
Wouldn't it be possible to use an armorstand with a CustomModelData head item, to render entities?

Thanks
hxr404

**Comment by RitikShah** [comment]
I think animations would be tough but technically possible. Hitboxes could require some invisible entity as well.
On top of that, you could generate the models for optifine / fabric-equivalence since those are very popular

**Comment by TheEpicBlock** [comment]
I definitely plan to add support for entities. But due to how they're done it will be tricky or maybe even impossible to automate the creation of the models. For now I'm working on improving other things but I should come to this when I'm finished with guis
