### ISSUE TITLE
Can you add support for 1.17 snapshots please?

### ISSUE THREAD

**Issue by Justsnoopy30** [TheEpicBlock/PolyMc#51]

**Comment by TheEpicBlock** [comment]
I'll probably start porting tomorrow :+1:

**Comment by Justsnoopy30** [comment]
Ty.

**Comment by TheEpicBlock** [comment]
#c6bdc6e *should* work on 20w46a. Let me know if I messed anything up! [Jar for convenience.](https://cdn.discordapp.com/attachments/742468225584857268/777566368093831198/polymc-2.3.020w46a.jar)
