### ISSUE TITLE
Opening a block with a modded gui destroys the item in the player's hand

### ISSUE THREAD

**Issue by TrueCP6** [TheEpicBlock/PolyMc#56]

**Comment by TheEpicBlock** [comment]
Was this on the master branch or on the guiAttemptTwo branch? If you're on master, did you try relogging? Could you also provide the mod you're having this issue with?

**Comment by TrueCP6** [comment]
This was on the latest build of the master branch with Charm. I didn't try relogging. The items occaisionally existed as ghost items where they were visible on the client but couldn't be used and would disappear when dropped. The item held debug command also returned air.

**Comment by TheEpicBlock** [comment]
I know that the gui implementation in the master branch causes massive inventory desync. But it usually fixes itself after moving some items around. This should be the bug you're experiencing. I'll merge the current progress in guiAttemptTwo soon™ and that should fix it

**Comment by TheEpicBlock** [comment]
I believe this has been fixed, as I couldn't reproduce this with Charm. If the issue persist please reopen :)
