### ISSUE TITLE
Support for blocks that emit light

### ISSUE THREAD

**Issue by TrueCP6** [TheEpicBlock/PolyMc#58]

**Comment by TheEpicBlock** [comment]
It seems that minecraft is quite happy to accept random blocks as light sources. When relogging they seem quite stable unless when placing blocks right next to them. Sending a lighting update packet when a modded light source is placed might be enough to convince the client.

**Comment by TheEpicBlock** [comment]
As of d9ae6aadbb5e4e76f737672b4b3c799fe2e65b3b this is now half-fixed. When placing blocks next to modded ones the client still decides to recalculate lighting.
