### ISSUE TITLE
Suggestion: Configurable list of blocks to prioritise

### ISSUE THREAD

**Issue by TrueCP6** [TheEpicBlock/PolyMc#60]
Blocks on this list would be given first dibs on a blockstate with the leftover blockstates being used for the remaining blocks.

**Comment by TrueCP6** [comment]
This would be a server wide setting.

**Comment by TheEpicBlock** [comment]
Implemented via [PolyPrioritize](https://github.com/TheEpicBlock/PolyPrioritize/)
