### ISSUE TITLE
Incompatibility with NBT-Crafting

### ISSUE THREAD

**Issue by lootjes** [TheEpicBlock/PolyMc#65]
PolyMc is in its default state not compatible with nbt crafting.
this occurs because the mixins for SynchronizeRecipesS2CPacket  conflict.
it can be fixed by adding it to the disabled mixins.

i would suggest adding the below entry(or similair more conforming) text to the mod compatibility page

## Nbt Crafting
Nbt Crafting is a mod which introduces nbt-related recipes.

Nbt Crafting's and PolyMc's implementation of a mixin in SynchronizeRecipesS2CPacket are incompatible.
luckily Nbt Crafting's implementation is a more sophisticated version. Compatibility can be achieved by disabling the mixin [`item.CustomRecipeFix`](https://github.com/TheEpicBlock/PolyMc/wiki/Config#itemcustomrecipefix)

**Comment by lootjes** [comment]
note that adding item.CustomRecipeFix to the disabled mixins does not seem to disable the mixin. adding CustomRecipeFix does.

Maybe clarify this on the config page?

**Comment by lootjes** [comment]
ok it seems to have broken again. guess i came to a conclusion too quickly. ill close this and open an issue when im more certain

**Comment by TheEpicBlock** [comment]
This is an issue with how NBT-Crafting [writes the size](https://github.com/Siphalor/nbt-crafting/blob/1.15-2.0/src/main/java/de/siphalor/nbtcrafting/mixin/network/MixinSynchronizeRecipesS2CPacket.java#L44). We're doing the same thing here, except he's doing things closer to the source. What would probably be the best solution here is to take the exact same route he's taking and make PolyMc override NBT-Crafting. As the mixin will get rid of all non-vanilla recipe types it should achieve the same thing anyway. So there's no issue with overriding him here.
