### ISSUE TITLE
Polymc is incompatible with REI.

### ISSUE THREAD

**Issue by QPCrummer** [TheEpicBlock/PolyMc#71]
If the player has all of the mods for the modded server and tries to look up a recipe, it won't let them. Also, if they activate "cheat mode", it will give you a random vanilla item instead of the modded item.

**Comment by QPCrummer** [comment]
I am using the latest Polymc

**Comment by TheEpicBlock** [comment]
If I understand correctly, you're using a client with all the mods on the PolyMc server. Doing this currently not supported. REI will think the server is a vanilla server, that *probably* why it's glitching out. 
In the next couple of days you'll be able to use a custom polymap per player. Effectively allowing you use a fully modded client just like any modded server, and have PolyMc only work for clients who don't have the mods.

**Comment by QPCrummer** [comment]
Thanks. You guys work so hard 👍
