### ISSUE TITLE
Support - REI,  Xaero's and so on...

### ISSUE THREAD

**Issue by usdbrl** [TheEpicBlock/PolyMc#75]
Hello again 😄 

I've noticed that those two mods, the REI which show the recipes of mods items and Xaero's Map are not work properly right now.
It's related with the GUIs support still in development?

I'm not very aware of coding or programming, but i just wanna ask if those things are related to that.

Thanks in advance.

**Comment by RDKRACZ** [comment]
GUIs don’t work yet
https://theepicblock.github.io/PolyMc/status.html

**Comment by usdbrl** [comment]
Yeah, i guessed looking the roadmap.
Thanks 👍

**Comment by TrueCP6** [comment]
Xaero's World Map and Minimap and (most of) REI are client side and thus can not work with PolyMC. You would need to make an alternative mod from scratch for each of these mods that works completely server side. From my understanding the goal of PolyMC does not include converting client side only mods to server side vanilla compatible mods and instead leaves it up to other mods to remake these features for the server side.

**Comment by usdbrl** [comment]
Now, i'm confused...

They are not working because of the non-support at the moment or because they are client-side related and cannot be applied on the server-side without recoding the mod?

**Comment by QPCrummer** [comment]
@usdbrl Do you mean that you cannot see recipes with REI. This should be fixed with the latest release I believe.

**Comment by usdbrl** [comment]
@QPCrummer The HUD and the recipes. 
The latest version released yesterday doesn't have a .jar file, i'm unable to test because of that.

The screenshot is how i see the game with both mods installed.

![Captura de tela 2021-02-12 130435](https://user-images.githubusercontent.com/70219462/107791581-e2745800-6d32-11eb-907e-e29b5735815a.jpg)

**Comment by QPCrummer** [comment]
@usdbrl Oh! REI is a client side mod meaning you must have it on your client to use it. You also have to install it on their server but it doesn’t do anything unless you have it on your client.

**Comment by usdbrl** [comment]
@QPCrummer I understand now.
Really appreciate the help. Thanks 👍

**Comment by TheEpicBlock** [comment]
Yes, like the people here have said, PolyMc is focused on making content mods possible to use serverside only. These mods that edit the gui heavily are pretty much impossible to do without modding the client.
