### ISSUE TITLE
Starting up PolyMC seems to change biomes and deletes the nether/end?

### ISSUE THREAD

**Issue by Raikaru** [TheEpicBlock/PolyMc#77]
PolyMC might have something going on with Biome Mods but every time I start it changes up all my biomes and deletes the nether/end. I have a Level.dat with the deleted nether/end if needed. I also have a backup of the old world and the changed world

**Comment by TheEpicBlock** [comment]
I doubt that this is an issue with PolyMc. It does not interfere with biomes or dimensions at all

**Comment by Raikaru** [comment]
It only happens when I start PolyMC. My level.dat gets Minecraft:the_end and Minecraft:the_nether removed and the biomes switch up

**Comment by TheEpicBlock** [comment]
Does adding `FabricRegistrySyncDisabler` to the `disabledMixins` part of the config fix this? The config should looks something like
```json
{
  "configVersion": 4,
  "disabledMixins": [
    "FabricRegistrySyncDisabler"
  ],
  "resourcepack": {
    "advancedDiscovery": false
etc
```

**Comment by Raikaru** [comment]
> Does adding `FabricRegistrySyncDisabler` to the `disabledMixins` part of the config fix this? The config should looks something like
> 
> ```json
> {
>   "configVersion": 4,
>   "disabledMixins": [
>     "FabricRegistrySyncDisabler"
>   ],
>   "resourcepack": {
>     "advancedDiscovery": false
> etc
> ```

I'm so so sorry for wasting your time and having the only semi legit issue being the Botania thing. This was a left over issue from the agape space mod's dimensions being in my level.dat and when they were erased it erased the nether/end too
