### ISSUE TITLE
Polymc isn't compatible with Tic-Tacs

### ISSUE THREAD

**Issue by QPCrummer** [TheEpicBlock/PolyMc#78]
This may sound bizarre but I think Polymc doesn't work with Tic-tacs. I have no clue how, but it creates an internal server error when joining. Here is the crash report:
[crash-2021-02-19_17.06.31-server.txt](https://github.com/TheEpicBlock/PolyMc/files/6013498/crash-2021-02-19_17.06.31-server.txt)
I have tried every mod individually with polymc and Tic-tacs was the only one that made it crash.

**Comment by TheEpicBlock** [comment]
I'm unsure how this has happened. It seems to crash whilst sending block updates to players. PolyMc slightly increases the time it takes to calculate the blocks as it has to look up the polyd version, but there should absolutely be no way it's taking long enough to kick in the server watchdog.

**Comment by QPCrummer** [comment]
Tic-tacs is multi-threaded. That could cause compatibility issues with other mods.
