### ISSUE TITLE
Error when running initial-setup.bat Polypack and few questions regarding PolyMC compatibility

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [TheEpicBlock/PolyMc#79]
**Issue description**

I downloaded the [PolyPack](https://www.curseforge.com/minecraft/modpacks/polypack) modpack, i ran initial-setup.bat, and during the mod download period i got this error every time the program attempted to download a mod.

`C:\Windows\System32\mods>curl https://media.forgecdn.net/files/3109/915/terrestria-2.1.5%2Bbuild.28.jar -O % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.`

Also, i would like to use the following mods with the PolyPack and I'm unsure wether they would work:

- [Cinderscapes](https://www.curseforge.com/minecraft/mc-mods/cinderscapes) ( I would assume this mod works, because PolyPack has other terrain generation mods and they work )
- [Origins](https://www.curseforge.com/minecraft/mc-mods/origins) ( I am unsure wether this mod will work as it does have a client-sided GUI )
- [Vanilla Death Chests](https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest-fabric)
- [Respawnable Pets](https://www.curseforge.com/minecraft/mc-mods/respawnable-pets)
- [Better End](https://www.curseforge.com/minecraft/mc-mods/BetterEnd)
- [Simple Harvest](https://www.curseforge.com/minecraft/mc-mods/simple-harvest)
- [Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) (Terrain Generation mod)
- [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn)
- [Reborn Core](https://www.curseforge.com/minecraft/mc-mods/reborncore)
- [Customizable Elytras](https://www.curseforge.com/minecraft/mc-mods/customizable-elytra-fabric)
- [Carrier](https://www.curseforge.com/minecraft/mc-mods/carrier)
- [CleanCut](https://www.curseforge.com/minecraft/mc-mods/cleancut)
- Any dependencies that these mods need

**Comment by TheEpicBlock** [comment]
I believe Cinderscape works. Origins probably doesn't. Vanilla death chests I'm unsure of, you'll have to try it. Respawnable pets works. I believe Better End works. Simple Harvest probably works. BYG works (except the stairs, slabs and a few others). Tech Reborn/ Reborn Core doesn't. Customizable Elytras won't work. Carrier *might* not apply the slowness, you'd have to try it. CleanCut I'm unsure of, you'll have to try it.

**Comment by TheEpicBlock** [comment]
Regarding the PolyPack issue. It's not an issue with PolyMc. I see you have created an issue on the PolyPack discord so I'll close this issue.

**Comment by Username-Is-Unavailabl** [comment]
Thank you for the help and for making PolyMC!
