### ISSUE TITLE
Modded Items and Blocks not showing up. No textures for Sugar Cane and Crossbow

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [TheEpicBlock/PolyMc#81]
I have setup a Fabric server with PolyMc [these mods](https://github.com/TrueCP6/PolyPack/wiki/Mod-list), I generated and installed the PolyMc resource pack onto the client, when the client joins the server, no modded items or blocks show up in Creative inventory and many more other issues.
I have tested these mods and they work when they are installed on the client, but with PolyMc it does not work.
This is very likely a problem from me and not PolyMc, but I am unsure what I did wrong.

**Comment by Obydux** [comment]
Items aren't gonna show up in the creative inventory because you're still using a vanilla client, it's normal behavior

**Comment by Username-Is-Unavailabl** [comment]
The resource pack is in the root folder of the server, also, there are many more issues, for example some things just don't work like crafting with the crafting bench in hand, most items are craftable but don't function, and many more issues...

**Comment by Obydux** [comment]
Wdym by "in the root folder"? The resource pack has to be hosted somewhere and you have to add it thru server.properties. Also, don't just say "... and more issues", list all of them.

**Comment by TheEpicBlock** [comment]
Like Oby said, items not showing up in the creative menu is expected. As you seem to be using PolyPack, there should already be a link set up so clients download the resource pack from the right url. I don't understand what you mean with `crafting with the crafting bench in hand`. And in what way do the items not function? I know some bugs in creative mode where items would be nullified, most commonly by using the middle-mouse-button to duplicate them. This might explain your behaviour.

**Comment by Username-Is-Unavailabl** [comment]
1. I don't want yet to set the server up for friends to join, I just generated the resource pack, put it in my .minecraft/resource packs and in the folder of the server
2. I was unable to set up PolyPack, i have just made a normal fabric server and put the exact mods the PolyPack has in it (and linked the PolyPack modlist out of laziness to make my own list)
3. When I said `crafting with the crafting bench in hand` i just said an example of an issue i have been facing (there is suposed to be a mod that allows the user to hold the crafting table in hand and right click and use it like that)
4. By many more issues I want to say that there are issues that normaly should not be and i dont think listing the issues would be helpful, because i think there is another problem that if I fix, the other issues dissapear.

**Comment by TheEpicBlock** [comment]
Okay, not all mods may work perfectly. The crafting table one might do their code in a way that it is triggered on the client. This isn't really solvable without remaking the mod. (Could you send a link to it?). Your issues may very well be real issues with PolyMc, it isn't perfect, there's not enough context here.
