### ISSUE TITLE
Issue: Poly stops working after creative menu is Opened (PolyMC 3.1.1)

### ISSUE THREAD

**Issue by MrVintage710** [TheEpicBlock/PolyMc#84]
So I think I found a small bug in the most recent version (3.1.1). While only in creative mode, if you have a poly item in your inventory and you open your inventory by pressing (E), the item is no longer a poly item. [Here is a video demonstrating this.](https://streamable.com/9j9v51) 

The item is just a poly that has a the **use** method overridden. (Note that the violent shaking is me slamming the right click button). If you need more info I can provide it.

**Comment by TheEpicBlock** [comment]
Should be fixed in latest dev with the merge of #44
