### ISSUE TITLE
[Suggestion] Add to Curseforge

### ISSUE THREAD

**Issue by DillonB07** [TheEpicBlock/PolyMc#87]
I would love to use this on my Aternos servers but Aternos doesn't allow mods from GitHub.
Would it be possible to upload to [CurseForge](https://curseforge.com)?

Aternos mod requirements: [https://support.aternos.org/hc/en-us/articles/360052255311#h_01EPF9S3W42P6KV2P5YJ9FSF6T](https://support.aternos.org/hc/en-us/articles/360052255311#h_01EPF9S3W42P6KV2P5YJ9FSF6T)

**Comment by TheEpicBlock** [comment]
Unfortunately I won't be putting PolyMc on curseforge, at least not for the time being. PolyMc isn't magic so you'll probably need to make your own mod to properly configure it anyway.
