### ISSUE TITLE
modded blocks wont show when mod is on client

### ISSUE THREAD

**Issue by humematt190** [TheEpicBlock/PolyMc#90]
i have polymc on my server with oh the biomes you'll go and i installed it onto my minecraft and when i join the server i see the remapped blocks instead of the actual modded block

**Comment by TheEpicBlock** [comment]
Do you have PolyPuck correctly installed on both the client and the server?

**Comment by humematt190** [comment]
oh i didn't know that was a thing thanks for telling me
