### ISSUE TITLE
Incompatibility with Inmis & DankStorage

### ISSUE THREAD

**Issue by CamperSamu** [TheEpicBlock/PolyMc#95]
# Comment with the names of the mods that are not working (if a workaround is present, add it in brakets [])
- ### 1.17
 - DankStorage (Crash when interacting with a dank container)
 - Inmis (GUI doesn't open with PolyPuck, works only without it, crash after putting items in)
 - (I'll update the list when I find new mods or someone publishes a comment... (maybe a markdown file in the repo root might be better?))

**Comment by TheEpicBlock** [comment]
Unless there's a single common issue among them (like lack of arrp support), I think it's best to keep track of these in separate issues. Could you include the crashlog for DankStorage?

**Comment by CamperSamu** [comment]
Give me a second to setup the server and i'll post both client and server log for Inmis and DankStorage

**Comment by CamperSamu** [comment]
## Inmis
Inmis on client with PolyPuck: https://hastebin.com/ewuwimigew.css
Inmis on server without PolyPuck: https://hastebin.com/wubejiqimi.sql (sometimes the server crashes after joining back and interacting again with the backpack. occasionally it actually puts items in the backpack but the same issue occurs)


## DankStorage
DankStorage without PolyPuck (client crashes with no error with it); https://hastebin.com/ugeqemoqov.properties
 - Sometimes the items get saved or the server freezes (the one time it worked I managed to get a stack of 72 carpets :S )

I'm not sending the full logs because they're dirty, I'm recicling the same test world for different mods and the console is full of "X chunk fail" or "Y item recipe removed" (I'm facing issues with Dank Storage and Inmis  on clean worlds with PolyMC too)

**Comment by TheEpicBlock** [comment]
Without Polypuck, both mods seem to trigger the same crash. A nullpointer in `ScreenHandler#copySharedSlots`. I have not yet investigated the code, but my guess is that for some reason a slot is set to null instead of an empty itemstack. I assume it crashes here because it's copying the player inventory to a new screen. Will have to investigate further

**Comment by TheEpicBlock** [comment]
After above commit, DankStorage no longer crashes (no polypuck). Instead it chooses to just stall indefinitely upon inserting an item. Inmis does the same thing. I'm going to say that's the same issue as #73

**Comment by TheEpicBlock** [comment]
It seems like the underlying issue in these mods has since been fixed, so I'm going to close this issue. If any issue persists please make a bugreport per mod :)
